services:
  influxdb3-core:
    image: influxdb:3.6-core
    container_name: influxdb3
    env_file:
      - influx.env
    command:
      - influxdb3
      - serve
      - --node-id=${INFLUX_NODE_ID}
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    ports:
      - "8181:8181"
    volumes:
      - influxdb3-data:/var/lib/influxdb3/data
      - influxdb3-plugins:/var/lib/influxdb3/plugins
    restart: unless-stopped

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    env_file:
      - grafana.env
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - influxdb3-core

  app-writer:
    build: ./app
    container_name: influx-writer
    env_file:
      - app/.env.app
    depends_on:
      - influxdb3-core
    restart: unless-stopped

volumes:
  influxdb3-data:
  influxdb3-plugins:
  grafana-data:
