# This compose dev is fo start and test dokcer compose 
services:
  # InfluxDB OSS 2
  influxdb3_core:
    image: influxdb:3.6-core
    container_name: Influx3_core
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      # The container's path to the file that contains th user name for the initial user
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      # The container's path to the faile that contains the password for the initial user
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      # The container's path to the file that contains a token to use for initial Operator Toke
      # If not defined, InfluxDB generates one automatically.
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      # Settings for the initial org and bucket
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_INIT_BUCKET}
  # Secret files
    secrets:
      - influxdb3-admin-username
      - influxdb3-admin-password
      - influxdb3-admin-token
    volumes:
      - type: volume
        source: influxdb3-data
        target: /var/lib/influxdb3/data
      - type: volume
        source: influxdb3-plugins
        target: /var/lib/influxdb3/plugins
    networks:
      - iot-network

secrets:
  influxdb3-admin-username:
    file: ./secrets/.env.influxdb3-admin-username
  influxdb3-admin-password:
    file: ./secrets/.env.influxdb3-admin-password
  influxdb3-admin-token:
    file: ./secrets/.env.influxdb3-admin-token

volumes:
  influxdb3-data:
  influxdb3-plugins:

networks:
  iot-network:
    driver: bridge
    # healthcheck:
    #   test: ["CMD", "influxdb2", "ping"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5