# Description
# Service InfluxDB 3 Core as the Time series database
# InfluxDB3 Explroer, for managing Influx DB3
services:
    # Influx DB 3 Core Service
  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3.6.0-core
    ports:
      - 8181:8181
    environment:
      - INFLUXDB3_ADMIN_TOKEN_FILE=run/secrets/influxdb_admin_token
      - INFLUXDB3_DATABASE_NAME=main
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    # Volumenes bind, cambiar a tipo named
    # para que asi docker los administre
    volumes:
      - type: bind
        source: ~/.influxdb3/core/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: ~/.influxdb3/core/plugins
        target: /var/lib/influxdb3/plugins
    secrets:
      - influxdb_admin_token
    networks:
      - iot-network

  explorer:
    image: influxdata/influxdb3-ui:1.4.0
    container_name: influxdb3-explorer
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    volumes:
      - ./config:/app-root/config:ro
    restart: unless-stopped
    networks:
      - iot-network

  telegraf:
    image: telegraf:1.36.3
    container_name: telegraf
    command: >
      sh -c "export INFLUX_TOKEN=$$(cat /run/secrets/influxdb2-admin-token) && exec telegraf"
    environment:
      MQTT_BROKER: ${MQTT_BROKER_URL}
      # Configuration output pluguin v2 to write on influxdb3
      INFLUX_SERVICE: influxdb3-core
      INFLUX_PORT: 8181
      DATABASE_NAME: ${INFLUX3_DATABASE}
      # For reading secrets from docker secrets telegraf use plugin
      # secretstores.docker
    secrets:
      - influxdb_admin_token
      - mqtt_broker
      - mqtt_user
    volumes:
    # Mount configurastion file
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb3-core
      # influxdb2:
      #   condition: service_healthy
    restart: always
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

secrets:
  grafana_admin_user:
    file: ./secrets/grafana_admin_user.env
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.env
  influxdb_admin_token:
    file: ./secrets/influxdb_admin_token.env
  mqtt_broker:
    file: ./secrets/mqtt_broker.env
  mqtt_user:
    file: ./secrets/mqtt_user.env
  mqtt_pass:
  file: ./secrets/mqtt_pass.env