name: Influx3_Grafana_Telegraf
services:
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana_service
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
        # This settigns will override the conf/grafana.ini
      - GF_DEFAULT_INSTANCE_NAME=GF_Main
      - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
      - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_password
      - API_TOKEN__FILE=/run/secrets/influxdb_admin_token
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    secrets:
      - grafana_admin_user
      - grafana_admin_password
      - influxdb_admin_token
    depends_on:
      - influxdb3-core
    networks:
      - iot-network

  influxdb3-core:
    container_name: influxdb3-core
    image: influxdb:3.6.0-core
    ports:
      - 8181:8181
    environment:
      - INFLUXDB3_ADMIN_TOKEN_FILE=run/secrets/influxdb_admin_token
      - INFLUXDB3_DATABASE_NAME=${INFLUX_DB_NAME}
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --plugin-dir=/var/lib/influxdb3/plugins
    # Volumenes bind, cambiar a tipo named
    # para que asi docker los administre
    volumes:
      - type: bind
        source: ~/.influxdb3/core/data
        target: /var/lib/influxdb3/data
      - type: bind
        source: ~/.influxdb3/core/plugins
        target: /var/lib/influxdb3/plugins
    secrets:
      - influxdb_admin_token
    networks:
      - iot-network

  explorer:
    image: influxdata/influxdb3-ui:1.4.0
    container_name: influxdb3-explorer
    command: ["--mode=admin"]
    ports:
      - "8888:80"
    volumes:
      - ./influxdb/config:/app-root/config:ro
    restart: unless-stopped
    networks:
      - iot-network

  telegraf:
    image: telegraf:1.36.3
    container_name: telegraf
    command: >
      sh -c "export INFLUXDB_TOKEN=$(cat /run/secrets/influxdbtoken_telegraf) && exec telegraf"
    environment:
      MQTT_BROKER: ${MQTT_BROKER_URL}
      # Configuration output pluguin v2 to write on influxdb3
      INFLUX_SERVICE: influxdb3-core
      INFLUX_PORT: 8181
      DATABASE_NAME: ${INFLUX_DB_NAME}
      # INFLUXDB_TOKEN: "apiv3_copperAplhaBravoRomeLima366!"
      # For reading secrets from docker secrets telegraf use plugin
      # secretstores.docker
    secrets:
      - influxdbtoken_telegraf
      - mqtt_broker
      - mqtt_user
    volumes:
    # Mount configurastion file
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb3-core
      # influxdb2:
      #   condition: service_healthy
    restart: always
    networks:
      - iot-network

networks:
  iot-network:
    driver: bridge

volumes:
  grafana-data:


secrets:
  grafana_admin_user:
    file: ./secrets/grafana_admin_user.env
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.env
  influxdb_admin_token:
    file: ./secrets/influxdb_admin_token.env
  influxdbtoken_telegraf:
    file: ./secrets/influxdbtoken_telegraf.env
  mqtt_broker:
    file: ./secrets/mqtt_broker.env
  mqtt_user:
    file: ./secrets/mqtt_user.env
  mqtt_pass:
    file: ./secrets/mqtt_pass.env