apiVersion: 1
deleteDatasources:
  - name: InfluxDB_v3_InfluxQL
    orgId: 1

datasources:
  - name: InfluxDB_v3_InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb3-core:8181
    jsonData:
      version: SQL
      dbName: new_database
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: apiv3_copperAplhaBravoRomeLima366!